name: Deploy SAP Integration API to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'function-app/msp_sap_integration/**'
      - '.github/workflows/api-deploy.yml'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even without changes'
        required: false
        default: 'false'

env:
  AZURE_WEBAPP_NAME: app-sap-integration-api-h7hwc9fwaugghnce
  PYTHON_VERSION: '3.11'
  RESOURCE_GROUP: marketing_controlling

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔍 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: 📦 Prepare deployment package
      run: |
        echo "🏗️  Creating deployment structure..."
        
        # Create clean deployment directory
        mkdir -p deploy-package
        
        # Copy API files
        echo "📁 Copying API files..."
        cp -r api/* deploy-package/
        
        # Copy processing logic from function-app
        echo "⚙️  Copying processing logic..."
        if [ -f "function-app/msp_sap_integration/msp_sap_integration_fixed.py" ]; then
          cp function-app/msp_sap_integration/msp_sap_integration_fixed.py deploy-package/
          echo "✅ Processing logic copied successfully"
        else
          echo "❌ Processing logic not found!"
          exit 1
        fi
        
        # Make startup script executable
        chmod +x deploy-package/startup.sh
        
        # Display package contents
        echo "📋 Deployment package contents:"
        ls -la deploy-package/
        
    - name: 🔧 Install dependencies and test
      run: |
        cd deploy-package
        
        echo "📦 Installing Python dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        echo "🧪 Testing imports..."
        python -c "
        try:
            import app
            print('✅ Flask app imports successfully')
            
            import flask
            print('✅ Flask available')
            
            import pandas as pd
            print('✅ Pandas available')
            
            import sqlalchemy
            print('✅ SQLAlchemy available')
            
            # Test if processing logic is importable
            try:
                from msp_sap_integration_fixed import DatabaseManager
                print('✅ Processing logic imports successfully')
            except ImportError as e:
                print(f'⚠️  Processing logic import warning: {e}')
            
            print('✅ All critical imports successful')
            
        except Exception as e:
            print(f'❌ Import test failed: {e}')
            exit(1)
        "
        
    - name: ☁️  Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 🚀 Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./deploy-package
        
    - name: ⚙️  Configure Azure Web App settings
      run: |
        echo "🔧 Configuring startup command..."
        az webapp config set \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --startup-file "startup.sh"
          
        echo "🔍 Verifying web app configuration..."
        az webapp config show \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --query "{startupFile: linuxFxVersion, pythonVersion: pythonVersion}"
        
    - name: 🏥 Health check after deployment
      run: |
        echo "⏳ Waiting for deployment to complete..."
        sleep 30
        
        echo "🔍 Testing API health check endpoint..."
        HEALTH_URL="https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health"
        
        # Try health check with retries
        for i in {1..5}; do
          echo "🩺 Health check attempt $i/5..."
          
          if curl -f -s "$HEALTH_URL" > /dev/null; then
            echo "✅ Health check passed!"
            curl -s "$HEALTH_URL" | jq '.status, .version, .azure_web_app.name'
            break
          else
            echo "⚠️  Health check failed, retrying in 15 seconds..."
            sleep 15
          fi
          
          if [ $i -eq 5 ]; then
            echo "❌ Health check failed after 5 attempts"
            echo "🔍 Checking Azure Web App logs..."
            az webapp log tail \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --provider application &
            sleep 10
            exit 1
          fi
        done
        
    - name: 📊 Post-deployment summary
      run: |
        echo ""
        echo "🎉 ====================================="
        echo "🚀 DEPLOYMENT COMPLETED SUCCESSFULLY!"
        echo "====================================="
        echo ""
        echo "🌐 API URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "🏥 Health Check: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health"
        echo "📊 Dashboard Data: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/data"
        echo "💼 Transactions: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/transactions"
        echo ""
        echo "📋 Key Endpoints:"
        echo "   - GET  /api/health - System status"
        echo "   - POST /api/process - Trigger data processing"
        echo "   - GET  /api/transactions - View transactions"
        echo "   - GET  /api/departments - Department summary"
        echo "   - GET  /api/outliers - Outlier analysis"
        echo "   - GET  /api/azure-info - Azure deployment info"
        echo ""
        echo "⚙️  Next Steps:"
        echo "   1. Configure DB_PASSWORD in Azure Web App settings"
        echo "   2. Test API endpoints"
        echo "   3. Run /api/process to generate initial data"
        echo "   4. Integrate with your frontend application"
        echo ""
        echo "🔧 Azure Configuration:"
        echo "   Resource Group: ${{ env.RESOURCE_GROUP }}"
        echo "   Subscription: Marketing-Kosten-Analytics"
        echo "   GitHub Repo: https://github.com/sadu619/Finanzen"
        echo "====================================="